name: CustomMobs
version: '${version}'
main: me.swishhyy.customMobs.CustomMobs
api-version: '1.21'
load: STARTUP
authors: [ Swishhyy ]

permissions:
  custommobs.admin:
    description: Full access to CustomMobs commands and update notices
    default: op

commands:
  cmspawn:
    description: Spawn a configured mob, reload configs, or run manual update
    usage: /cmspawn <mobId>|reload|update|updatebeta
    permission: custommobs.admin
