name: CustomMobs
version: '${version}'
description: A Custom Mob Framework implementation.
website: https://github.com/Swishhyy/CustomMobs
main: me.swishhyy.customMobs.CustomMobs
api-version: '1.21'
load: STARTUP
authors: [ Swishhyy ]

permissions:
  custommobs.admin:
    description: Full access to CustomMobs commands and update notices
    default: op

commands:
  cm:
    description: Root command for CustomMobs (reload, update, spawn, etc.)
    usage: /cm <reload|update|updatebeta|spawn>
    permission: custommobs.admin
