name: CustomMobs
version: '${version}'
main: me.swishhyy.customMobs.CustomMobs
api-version: '1.21'
load: STARTUP
authors: [ Swishhyy ]

commands:
	cmspawn:
		description: Spawn a configured mob by id
		usage: /cmspawn <mobId>
		permission: custommobs.spawn
